### ISSUE TITLE
How do I Associate another table ?

### ISSUE THREAD

**Issue by natarajanmca11** [suksant/sequelize-typescript-examples#1]
I want to know how to associate another table ?
One to many, Man to many etc.

Please provide sample with above details.

**Comment by suksant** [comment]
You need to add an association in your model(s) such as:

```
classMethods: {
    associate: (models: QTrackerModels) => {
        Role.belongsToMany(models.Operation, ({
            as: "operations",
            through: "RoleOperation"
        }) as any);
    }
}
```

The above will generate a table for many to many association between Role and Operation (ref: http://docs.sequelizejs.com/en/latest/api/associations/belongs-to-many/). For one to many, please refer to http://docs.sequelizejs.com/en/latest/api/associations/has-many/. You may see that in TypeScript, I am casting the options as `any`. This depends on the type definition version you have - some of which is not always up to date or accurate. You may fork your own type definition to keep it in sync with the current version of sequelize (you can also contribute back to the [DefinitelyTyped](http://definitelytyped.org/)).
